CONFIG_GPIO=y
CONFIG_SPI=y
CONFIG_LOG=y
# CONFIG_LED_STRIP=y
CONFIG_RGBW_STRIP=y
# CONFIG_LED_STRIP_LOG_LEVEL_DBG=y

# Button and LED library
CONFIG_DK_LIBRARY=y

# Floating Point Unit
CONFIG_FPU=y

# Bluetooth LE
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_NAME="test123"
CONFIG_BT_GATT_CLIENT=y

# Bluetooth Connection Parameters
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=800
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=800
CONFIG_BT_PERIPHERAL_PREF_LATENCY=0
CONFIG_BT_PERIPHERAL_PREF_TIMEOUT=400
CONFIG_BT_GAP_AUTO_UPDATE_CONN_PARAMS=y
CONFIG_BT_USER_PHY_UPDATE=y

# Bluetooth LE Monitor Mode Debugging
CONFIG_CORTEX_M_DEBUG_MONITOR_HOOK=y
CONFIG_SEGGER_DEBUGMON=y

# Coredump config
CONFIG_DEBUG_COREDUMP=y
CONFIG_DEBUG_COREDUMP_BACKEND_LOGGING=y

# Add LBS service
CONFIG_BT_LBS=y

# Increase stack size for the main thread, System Workqueue, BT RX thread and TX buf count
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
CONFIG_BT_RX_STACK_SIZE=2048
CONFIG_BT_BUF_CMD_TX_COUNT=2

# Enable **psuedorandom** number generator for testing purposes
CONFIG_TEST_RANDOM_GENERATOR=y